### ISSUE TITLE
duplicate library?

### ISSUE THREAD

**Issue by literalpie** [mygu/ngx-animate#1]
Is this library just a duplicate/fork of ng-animate? I cannot find any changes compared to that one.

**Comment by mygu** [comment]
@literalpie Yes, because the original library was not updated, and only supports `Angular 4.2+`. My team needs `Angular 5.0+`, so the library was built.

**Comment by owen26** [comment]
is it possible to upgrade dependencies to Angular 6+ ?

**Comment by mygu** [comment]
Hi @owen26, I see the original author has replied and started to update, you can wait a while. ([https://github.com/jiayihu/ng-animate/issues/4](https://github.com/jiayihu/ng-animate/issues/4)). I publish the `ngx-animate` version of `1.0.1`, but it's just a simple open `NPM` limit  to support `Angular 6+`. I didn't do enough testing, if you want, you can try it.

**Comment by owen26** [comment]
Thanks, I'll report back if there are any compatibility issues. I used it in my big project that recently upgraded to ng6 and it's so far working fine.

**Comment by mygu** [comment]
@owen26 I'm honored to give you some help :)

**Comment by maxisam** [comment]
it seems like the original one supports v6 and uses angular-cli to generate the package now.
